version: 1.0.{build}
image: Visual Studio 2017


environment:
  matrix:
    - PlatformToolset: VS15
    - PlatformToolset: VS17

platform:
    - Any CPU

configuration:
    - Release
    - Debug

install:

    - if "%platform%"=="Any CPU" set archi=x86
    - if "%platform%"=="Any CPU" set platform_input=Any CPU

    - if "%PlatformToolset%"=="VS15" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%
    - if "%PlatformToolset%"=="VS17" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%
    - nuget restore "%APPVEYOR_BUILD_FOLDER%"\DeviceExplorer\packages.config     -PackagesDirectory "%APPVEYOR_BUILD_FOLDER%"\packages
    - nuget restore "%APPVEYOR_BUILD_FOLDER%"\DeviceExplorerMvvm\packages.config -PackagesDirectory "%APPVEYOR_BUILD_FOLDER%"\packages
    - nuget restore "%APPVEYOR_BUILD_FOLDER%"\Devices\packages.config            -PackagesDirectory "%APPVEYOR_BUILD_FOLDER%"\packages


build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild WpfExplorer.sln /m /verbosity:minimal /t:Explorer;DeviceExplorer;DeviceExplorerMvvm;Devices /p:configuration="%configuration%" /p:platform="%platform_input%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-
        Push-AppveyorArtifact "Explorer\bin\$env:CONFIGURATION\Explorer.dll" -FileName Explorer.dll

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "VS17") {
            $ZipFileName = "WpfExplorer_$($env:APPVEYOR_REPO_TAG_NAME).zip"
            7z a $ZipFileName Explorer\bin\$env:CONFIGURATION\Explorer.dll
        }

# artifacts:
  # - path: WpfExplorer_*.zip
    # name: releases

# deploy:
    # provider: GitHub
    # auth_token:
        # secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    # artifact: releases
    # draft: false
    # prerelease: false
    # force_update: true
    # on:
        # appveyor_repo_tag: true
        # PlatformToolset: v141
        # configuration: Release
